--insercao autor
insert into autor (id_autor, Nome, biografia) values (1, 'Reinald Baskeyfied', 'Data Coordinator');
insert into autor (id_autor, Nome, biografia) values (2, 'Essa Forty', 'Physical Therapy Assistant');
insert into autor (id_autor, Nome, biografia) values (3, 'Keefer Bilverstone', 'Director of Sales');
insert into autor (id_autor, Nome, biografia) values (4, 'Mikel Cowton', 'Safety Technician III');
insert into autor (id_autor, Nome, biografia) values (5, 'Feliks MacCome', 'Structural Analysis Engineer');
insert into autor (id_autor, Nome, biografia) values (6, 'Bibbye Swale', 'Quality Control Specialist');
insert into autor (id_autor, Nome, biografia) values (7, 'Bobbe Leavy', 'VP Sales');
insert into autor (id_autor, Nome, biografia) values (8, 'Vassili Gossage', 'Budget/Accounting Analyst III');
insert into autor (id_autor, Nome, biografia) values (9, 'Aland Cleve', 'Cost Accountant');
insert into autor (id_autor, Nome, biografia) values (10, 'Carlene Sheirlaw', 'Social Worker');
insert into autor (id_autor, Nome, biografia) values (11, 'Noam Wallsworth', 'Physical Therapy Assistant');
insert into autor (id_autor, Nome, biografia) values (12, 'Townie Austins', 'Senior Developer');
insert into autor (id_autor, Nome, biografia) values (13, 'Efren Trimme', 'Occupational Therapist');
insert into autor (id_autor, Nome, biografia) values (14, 'Barnabas Tweedle', 'Data Coordinator');
insert into autor (id_autor, Nome, biografia) values (15, 'Caryl Cussons', 'Legal Assistant');
insert into autor (id_autor, Nome, biografia) values (16, 'Franny Stagg', 'Marketing Assistant');
insert into autor (id_autor, Nome, biografia) values (17, 'Gwenore Jeanel', 'Accountant I');
insert into autor (id_autor, Nome, biografia) values (18, 'Blakeley Joskowicz', 'Operator');
insert into autor (id_autor, Nome, biografia) values (19, 'Devonna Spykings', 'Desktop Support Technician');
insert into autor (id_autor, Nome, biografia) values (20, 'Janie Fatkin', 'Librarian');
insert into autor (id_autor, Nome, biografia) values (21, 'Shela Ohrt', 'Human Resources Assistant II');
insert into autor (id_autor, Nome, biografia) values (22, 'Hyacinthie Toogood', 'Automation Specialist IV');
insert into autor (id_autor, Nome, biografia) values (23, 'Maryl Frounks', 'Technical Writer');
insert into autor (id_autor, Nome, biografia) values (24, 'Gratia Jermin', 'Safety Technician IV');
insert into autor (id_autor, Nome, biografia) values (25, 'Adrianne Rouge', 'Data Coordinator');
insert into autor (id_autor, Nome, biografia) values (26, 'Kelsey Cicchillo', 'Social Worker');
insert into autor (id_autor, Nome, biografia) values (27, 'Abner Bamlett', 'Payment Adjustment Coordinator');
insert into autor (id_autor, Nome, biografia) values (28, 'Jacinthe Wingeat', 'Human Resources Assistant II');
insert into autor (id_autor, Nome, biografia) values (29, 'Elfrida Lamperd', 'Junior Executive');
insert into autor (id_autor, Nome, biografia) values (30, 'Bert Aspel', 'Sales Representative');
insert into autor (id_autor, Nome, biografia) values (31, 'Aviva Gowing', 'Project Manager');
insert into autor (id_autor, Nome, biografia) values (32, 'Trixi Terrazzo', 'Nuclear Power Engineer');
insert into autor (id_autor, Nome, biografia) values (33, 'Faina Bakhrushkin', 'Marketing Assistant');
insert into autor (id_autor, Nome, biografia) values (34, 'Wiley Gehring', 'Sales Associate');
insert into autor (id_autor, Nome, biografia) values (35, 'Alberta Robertsson', 'Paralegal');
insert into autor (id_autor, Nome, biografia) values (36, 'Redford Janicki', 'Product Engineer');
insert into autor (id_autor, Nome, biografia) values (37, 'Terrence Ottewill', 'Geologist III');
insert into autor (id_autor, Nome, biografia) values (38, 'Brantley Wedge', 'Account Executive');
insert into autor (id_autor, Nome, biografia) values (39, 'Aldridge Billingsley', 'Senior Developer');
insert into autor (id_autor, Nome, biografia) values (40, 'Robin McGaffey', 'Media Manager IV');
insert into autor (id_autor, Nome, biografia) values (41, 'Nels Clemits', 'Safety Technician II');
insert into autor (id_autor, Nome, biografia) values (42, 'Shelden Dooly', 'Technical Writer');
insert into autor (id_autor, Nome, biografia) values (43, 'Dexter Stiell', 'Human Resources Assistant III');
insert into autor (id_autor, Nome, biografia) values (44, 'Doreen Melmeth', 'General Manager');
insert into autor (id_autor, Nome, biografia) values (45, 'Ryon Norker', 'Software Consultant');
insert into autor (id_autor, Nome, biografia) values (46, 'Artair Coryndon', 'Registered Nurse');
insert into autor (id_autor, Nome, biografia) values (47, 'Barb McGregor', 'Product Engineer');
insert into autor (id_autor, Nome, biografia) values (48, 'Gabie Realff', 'VP Marketing');
insert into autor (id_autor, Nome, biografia) values (49, 'Jobie Bussen', 'Help Desk Operator');
insert into autor (id_autor, Nome, biografia) values (50, 'Kyle Brozsset', 'Analog Circuit Design manager');

-- insercao editora
insert into editora (id_editora, Nome) values (1, 'Youspan');
insert into editora (id_editora, Nome) values (2, 'Roombo');
insert into editora (id_editora, Nome) values (3, 'Bluejam');
insert into editora (id_editora, Nome) values (4, 'Kamba');
insert into editora (id_editora, Nome) values (5, 'Skaboo');
insert into editora (id_editora, Nome) values (6, 'Voonyx');
insert into editora (id_editora, Nome) values (7, 'Chatterpoint');
insert into editora (id_editora, Nome) values (8, 'Twitterwire');
insert into editora (id_editora, Nome) values (9, 'Zoonder');
insert into editora (id_editora, Nome) values (10, 'Flashpoint');
insert into editora (id_editora, Nome) values (11, 'Wikido');
insert into editora (id_editora, Nome) values (12, 'Flashspan');
insert into editora (id_editora, Nome) values (13, 'Geba');
insert into editora (id_editora, Nome) values (14, 'Babbleopia');
insert into editora (id_editora, Nome) values (15, 'Yoveo');

--insercao cliente
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (1, '232.862.675-32', 'Blaire Snalum', '12.07.2023', 0, '213 Nelson Junction');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (2, '415.311.308-36', 'Andee Hapgood', '26.08.2022', 0, '68585 Kipling Junction');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (3, '698.010.057-44', 'Madlin Ranner', '01.01.2023', 0, '0 American Ash Court');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (4, '462.959.027-55', 'Stephanie Milier', '02.04.2024', 0, '99905 Hallows Circle');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (5, '034.821.067-49', 'Ainsley Yurocjkin', '18.10.2021', 0, '482 Maple Wood Hill');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (6, '816.404.130-78', 'Marcelo Landrean', '17.12.2020', 0, '25030 Nelson Lane');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (7, '550.785.205-17', 'Latrena Heskins', '08.04.2021', 0, '5729 Ryan Avenue');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (8, '686.270.154-23', 'Benjy Bilovsky', '18.04.2022', 0, '89965 Dexter Lane');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (9, '326.024.495-94', 'Gardy Stanyland', '02.11.2022', 0, '26125 Montana Parkway');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (10, '673.337.199-40', 'Normand Kitchener', '18.08.2022', 0, '2687 Mendota Lane');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (11, '581.726.793-28', 'Padraig Charters', '21.08.2022', 0, '09286 Manitowish Drive');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (12, '627.920.533-62', 'Ethelda Butte', '29.05.2022', 0, '86 Stuart Point');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (13, '744.642.077-95', 'Doloritas Gynne', '15.07.2021', 0, '5 International Court');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (14, '844.250.573-75', 'Ettore Somersett', '10.09.2023', 0, '54568 Hoepker Drive');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (15, '994.470.572-67', 'Kenny Curl', '13.07.2023', 0, '69829 Scofield Junction');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (16, '543.061.228-00', 'Iain Lundon', '29.01.2024', 0, '67 Lake View Point');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (17, '240.418.124-97', 'Henrie Peach', '12.10.2022', 0, '4061 Independence Trail');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (18, '722.821.229-59', 'Barry Earey', '20.11.2021', 0, '60 Bluejay Drive');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (19, '743.793.437-10', 'Elfie Feirn', '19.11.2022', 0, '09906 Homewood Center');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (20, '554.432.104-69', 'Walden Edmondson', '24.06.2024', 0, '81 Towne Lane');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (21, '070.924.259-03', 'Zared Tyce', '19.11.2020', 0, '96596 Dryden Road');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (22, '323.838.680-29', 'Zared Abramcik', '21.06.2021', 0, '2 Everett Court');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (23, '481.439.856-15', 'Alain Etteridge', '15.12.2021', 0, '205 Butterfield Drive');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (24, '367.737.969-44', 'Brit Popplewell', '08.05.2023', 0, '9571 Mccormick Hill');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (25, '795.680.633-50', 'Catlin Lapenna', '19.06.2023', 0, '49997 Johnson Drive');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (26, '171.226.403-22', 'Milo Parry', '30.10.2022', 0, '31 Jenifer Terrace');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (27, '558.281.873-97', 'Nanny Georgius', '14.08.2020', 0, '28956 Butterfield Street');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (28, '130.786.385-24', 'Worthy Sumers', '02.03.2024', 0, '54 Everett Street');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (29, '620.872.643-64', 'Arron Torregiani', '04.08.2021', 0, '58768 Fisk Point');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (30, '282.393.840-35', 'Susanna Mullis', '06.09.2020', 0, '924 Lakeland Crossing');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (31, '525.022.047-95', 'Rudie Elintune', '04.04.2024', 0, '88053 Debs Crossing');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (32, '383.534.896-77', 'Valida Lebarree', '26.01.2023', 0, '575 Sundown Pass');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (33, '801.936.224-29', 'Riobard Wynes', '23.02.2021', 0, '1 Green Street');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (34, '511.915.126-15', 'Cathleen Fussie', '26.06.2023', 0, '5078 Lakewood Way');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (35, '567.688.242-72', 'Fawn Duferie', '27.12.2022', 0, '2158 Dexter Junction');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (36, '763.405.618-27', 'Clark Lightwing', '21.08.2021', 0, '41220 Fieldstone Junction');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (37, '036.038.490-35', 'Piggy Everley', '06.11.2020', 0, '494 Stephen Alley');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (38, '810.273.197-35', 'Ward Chomley', '24.06.2022', 0, '9 Macpherson Center');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (39, '408.910.989-05', 'Donella Burke', '13.01.2023', 0, '7 Aberg Parkway');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (40, '803.470.135-22', 'Guillaume Fayne', '13.01.2023', 0, '45353 Summit Drive');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (41, '147.642.383-00', 'Sunshine Paylie', '17.09.2021', 0, '687 Kim Pass');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (42, '133.508.052-14', 'Alexandre Jouhandeau', '20.09.2022', 0, '0 Melvin Court');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (43, '128.055.074-23', 'Marwin Mummery', '21.05.2023', 0, '354 Anhalt Terrace');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (44, '500.150.108-04', 'Eleen Braban', '02.01.2022', 0, '84809 Prairieview Hill');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (45, '718.590.243-65', 'Daveen Trevon', '30.10.2023', 0, '645 Ramsey Court');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (46, '162.475.972-84', 'Junina Eubank', '24.11.2021', 0, '2 Morning Road');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (47, '606.585.064-33', 'Lana Antonnikov', '01.12.2020', 0, '2 Drewry Alley');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (48, '976.296.829-98', 'Sharona Beslier', '24.05.2024', 0, '2 Rieder Park');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (49, '444.584.878-32', 'Titos Stedman', '12.11.2020', 0, '8085 Nevada Junction');
insert into cliente (id_cliente, CPF, Nome, data_reg, numero_emp, endereco) values (50, '874.529.780-95', 'Wenda Gaitskell', '08.04.2024', 0, '56 Miller Road');


--insercao bibliotecario
insert into bibliotecario(id_bibli, nome_biblio, data_ent, endereco) values (1, 'marcelo silva', '11.03.2020', 'avenida tupi 1500');
insert into bibliotecario(id_bibli, nome_biblio, data_ent, endereco) values (2, 'andreia conceicao', '15.06.2022', 'rua duque de caxias 150');
insert into bibliotecario(id_bibli, nome_biblio, data_ent, endereco) values (3, 'marcos neto', '23.010.2023', 'avenida iguacu 75');

--insercao livro
